### ISSUE TITLE
Array query params wrongly generated 

### ISSUE THREAD

**Issue by acrontum-sanchez** [acrontum/openapi-nodegen#10]
When defining a query parameter like:

`in: query
name: products
type: array
required: true
items:
  type: string
`

Then the generated interface looks like:

`export default interface MarketToolProductsLanguageGetQuery {
  products: array;
}
`

instead of:

`export default interface MarketToolProductsLanguageGetQuery {
  products: Array<string> ; // or string[];
}
`

**Comment by Acrontum-Carmichael** [comment]
The culprit in question here @acrontum-sanchez  is this line:

https://github.com/acrontum/openapi-nodegen/blob/master/lib/generateSwaggerDefinitionToTypescriptInterface.js#L41

Which is called in the initial bundler:
https://github.com/acrontum/openapi-nodegen/blob/master/lib/OpenAPIBundler.js#L48

**Comment by Acrontum-Carmichael** [comment]
@acrontum-revah would be great if you could take a look at this one with Santi

**Comment by Acrontum-Carmichael** [comment]
fixed with v4 and use of quicktype
