### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by acrontum-sanchez** [acrontum/openapi-nodegen#16]
**Describe the bug**
When the swagger file does not contain any definition, the node generation fails.

**To Reproduce**
1. Create a swagger file without definitions
2. Run the nodegen

**Expected behavior**
The node app generation should not fail

**Node & NPM version**
node v10.17

**Operating system:**
 - OS: Linux

**Additional context**

**Comment by Acrontum-Carmichael** [comment]
4.3.1 version just published fixes this issue. Tests to catch in the future.
