### ISSUE TITLE
Swagger validations not added to the Joi validations.

### ISSUE THREAD

**Issue by acrontum-sanchez** [acrontum/openapi-nodegen#3]
Swagger validations are not being added to the Joi validations.

Example of swagger yml:

`myVariable:
    in: query
    name: text
    required: true
    type: string
    minLength: 7
    maxLength: 17
`
  Result:

`export default {
  customerGet: {
    query: {
      text: Joi.string()
        .allow("")
        .required()
    }
  }
};`

The min and max length validations are missing.

**Comment by Acrontum-Carmichael** [comment]
released on 2.4.0 (min max values to the joi validation middleware)
