### ISSUE TITLE
422 error code is not available.

### ISSUE THREAD

**Issue by acrontum-sanchez** [acrontum/openapi-nodegen#4]
I can not throw custom 422 errors.  Only through Joi. 

I would like to be able to throw `new http422(errors); `

**Comment by Acrontum-Carmichael** [comment]
We will need to ensure that the same 422 error from the celebrate lib is used so that the format of the returned object matches other 422 errors.

**Comment by Acrontum-Carmichael** [comment]
@acrontum-sanchez  would be great if you could write a custom middleware to handle this type of 422, once you know what is needed ping it on here and we can introduce it to the main code base.

**Comment by Acrontum-Carmichael** [comment]
this is now template specific and not to do with the core.

however, the templates now make use of a later version of celebrate which offer error format allowing 422 to be thrown in a domain and caught by the handler
