### ISSUE TITLE
Add models for transformers 

### ISSUE THREAD

**Issue by acrontum-sanchez** [acrontum/openapi-nodegen#5]
Would be great to generate interfaces for the transformers.

I would like to use the following generated transformer as a type in other parts of the application.
`
export default {
  // customerGet
  customerGet: {
    email: String,
    firstName: String,
    lastName: String
  }
};

`
Would like to have something like this:

`
export interface CustomerGet {
    email: String,
    firstName: String,
    lastName: String
  }

export default {
  // customerGet
  customerGet: CustomerGet
};
`

**Comment by Acrontum-Carmichael** [comment]
released 2.5.0
